const fs = require('fs');
const path = require('path');

// MASTER TRANSLATION DICTIONARY (Merged from all individual passes)
const dict = {
  "Laporan Performa": "Performance Report",
  "Ringkasan metrik dan pendapatan. Default menampilkan semua data.": "Summary of metrics and revenue. By default displays all data.",
  "Bulan/Tahun": "Month/Year",
  "Bulan & Tahun": "Month & Year",
  "Rentang Tanggal": "Date Range",
  "Status Transaksi": "Transaction Status",
  "Terapkan Filter": "Apply Filter",
  "Tutup": "Close",
  "Batal": "Cancel",
  "Simpan": "Save",
  "Ubah": "Edit",
  "Hapus": "Delete",
  "Ya, Hapus": "Yes, Delete",
  "Menyiapkan Laporan Lengkap...": "Preparing Full Report...",
  "Memuat semua data transaksi": "Loading all transaction data",
  "baris": "rows",
  "Layanan Terpopuler": "Popular Services",
  "Pendapatan": "Revenue",
  "Pelanggan": "Customer",
  "Kapster": "Barber",
  "Layanan": "Service",
  "Kode": "Code",
  "Semua Waktu": "All Time",
  "Periode:": "Period:",
  "Daftar Transaksi Terbaru": "Recent Transactions",
  "Selesai": "Completed",
  "Diproses": "Processing",
  "Hadir": "Arrived",
  "Dibatalkan": "Cancelled",
  "Semua": "All",
  "Gagal memuat laporan.": "Failed to load report.",
  "Gagal memuat transaksi.": "Failed to load transactions.",
  "Gagal menyiapkan data cetak lengkap.": "Failed to prepare print data.",
  "Menyiapkan Laporan": "Preparing Report",
  "Apakah Anda yakin ingin menghapus promo ini secara permanen?": "Are you sure you want to permanently delete this promo?",
  "Promo berhasil dihapus.": "Promo successfully deleted.",
  "Gagal menghapus promo.": "Failed to delete promo.",
  "Promo berhasil diperbarui!": "Promo successfully updated!",
  "Promo berhasil dibuat!": "Promo successfully created!",
  "Gagal menyimpan promo": "Failed to save promo",
  "Belum ada promo.": "No promos available.",
  "Kini": "Now",
  "Seterusnya": "Onwards",
  "Tanpa Batas": "No Limit",
  "Tukar Poin": "Redeem Points",
  "Layanan Khusus": "Specific Service",
  "Layanan Tertentu": "Specific Services",
  "Semua Layanan": "All Services",
  "Khusus:": "Specific:",
  "Tidak berlaku untuk layanan ini": "Not applicable for this service",
  "Member Baru": "New Member",
  "Keluar": "Logout",
  "Antrian": "Queue",
  "Pengaturan": "Settings",
  "Promosi": "Promotions",
  "Laporan": "Reports",
  "Jadwal": "Schedule",
  "Gagal memuat data": "Failed to load data",
  "Memuat...": "Loading...",
  "Berhasil": "Success",
  "Informasi": "Information",
  "Kesalahan": "Error",
  "Peringatan": "Warning",
  "Konfirmasi": "Confirmation",
  "Kembali": "Back",
  "Masuk": "Log In",
  "Daftar": "Register",
  "Lupa Password": "Forgot Password",
  "Belum punya akun?": "Don't have an account?",
  "Sudah punya akun?": "Already have an account?",
  "Tambah Layanan": "Add Service",
  "Tambah Kapster": "Add Barber",
  "Nama Layanan": "Service Name",
  "Harga": "Price",
  "Deskripsi": "Description",
  "Gambar": "Image",
  "Waktu (Menit)": "Time (Minutes)",
  "Aksi": "Action",
  "Edit Layanan": "Edit Service",
  "Layanan berhasil ditambahkan!": "Service successfully added!",
  "Layanan berhasil diubah!": "Service successfully updated!",
  "Layanan berhasil dihapus!": "Service successfully deleted!",
  "Kapster berhasil ditambahkan!": "Barber successfully added!",
  "Kapster berhasil diubah!": "Barber successfully updated!",
  "Kapster berhasil dihapus!": "Barber successfully deleted!",
  "Tidak ada layanan": "No services available",
  "Tidak ada kapster": "No barbers available",
  "Presisi dalam Setiap Potongan": "Precision in Every Cut",
  "Klaim": "Claim",
  "Pilih Layanan": "Select Service",
  "Lanjut ke Pembayaran": "Proceed to Payment",
  "Lanjut": "Next",
  "Metode Pembayaran": "Payment Method",
  "Jam": "Time",
  "Tanggal": "Date",
  "Pilih Jadwal": "Select Schedule",
  "Konfirmasi Pesanan": "Confirm Booking",
  "Catatan": "Notes",
  "Opsional": "Optional",
  "Pesan Sesi": "Book Session",
  "memadukan teknik tradisional dengan gaya modern yang tajam.": "combines traditional techniques with sharp modern styles.",
  "Booking Sekarang": "Book Now",
  "Interior Barbershop Mewah": "Luxury Barbershop Interior",
  "Presisi dalam": "Precision in",
  "Setiap Potongan": "Every Cut",
  "Lihat Menu Service": "View Service Menu",
  "Service Unggulan": "Featured Services",
  "Lihat All Services": "View All Services",
  "Penawaran Spesial": "Special Offers",
  "Promo & Diskon": "Promo & Discounts",
  "Diskon Member Baru": "New Member Discount",
  "Dapatkan potongan harga 20rb khusus untuk member baru yang telah mendaftar. Berlaku untuk semua layanan.": "Get a 20k discount exclusively for newly registered members. Valid for all services.",
  "Tukarkan 100 poin kamu dan dapatkan diskon 50rb untuk potongan rambut atau layanan lainnya.": "Redeem 100 points and get a 50k discount for a haircut or other services.",
  "Register Member Sekarang": "Register as Member Now",
  "Status Antrean": "Queue Status",
  "Ketersediaan Barber": "Barber Availability",
  "Lihat All Barber": "View All Barbers",
  "Year Pengalaman": "Years of Experience",
  "Mengapa Memilih": "Why Choose",
  "Barber Profesional": "Professional Barbers",
  "Suasana Eksklusif": "Exclusive Atmosphere",
  "Nikmati interior bertema industrial-klasik yang tenang dan nyaman.": "Enjoy a calm and comfortable classic-industrial themed interior.",
  "Produk Premium": "Premium Products",
  "Petunjuk Arah": "Get Directions",
  "Siap Untuk Tampilan Baru?": "Ready For a New Look?",
  "di kota ini. Antrean berjalan cepat, namun kualitas tetap utama.": "in town. The queue moves fast, but quality remains our priority.",
  "Time Operasional": "Operational Hours",
  "Presisi dalam setiap potongan.": "Precision in every cut.",
  "Tentang Kami": "About Us",
  "Kebijakan Privasi": "Privacy Policy",
  "Syarat & Ketentuan": "Terms & Conditions",
  "Hubungi Kami": "Contact Us",
  "Reservasi Sesi Presisi": "Precision Session Reservation",
  "Select Service Utama": "Select Main Service",
  "Pijat Kepala": "Head Massage",
  "Cukur jenggot": "Beard Trim",
  "Atur Waktu Kedatangan": "Set Arrival Time",
  "Slot Time Tersedia": "Available Time Slots",
  "Sudah Lewat": "Passed",
  "Select Barber": "Select Barber",
  "Silakan pilih slot waktu terlebih dahulu untuk melihat kapster yang tersedia.": "Please select a time slot first to view available barbers.",
  "Tanpa Promo": "No Promo",
  "Nextkan tanpa menggunakan promo atau diskon.": "Continue without using a promo or discount.",
  "Ringkasan Sesi": "Session Summary",
  "Waktu Kedatangan": "Arrival Time",
  "Select Time": "Select Time",
  "Anyone (Tersedia)": "Anyone (Available)",
  "Confirmation Schedule": "Confirm Schedule",
  "Confirmation Identitas": "Identity Confirmation",
  "Nextkan Cepat": "Quick Continue",
  "Log In Member": "Member Login",
  "LANJUTKAN BOOKING": "CONTINUE BOOKING",
  "Mengapa Member?": "Why Become a Member?",
  "Dapatkan Keuntungan Lebih": "Get More Benefits",
  "Poin Loyalitas": "Loyalty Points",
  "Kumpulkan poin di setiap kunjungan dan tukarkan dengan layanan gratis atau produk eksklusif.": "Collect points on every visit and redeem them for free services or exclusive products.",
  "Riwayat Presisi": "Precision History",
  "Prioritas Antrean": "Queue Priority",
  "Member mendapatkan slot waktu prioritas dan kemudahan untuk reschedule kapan saja.": "Members get priority time slots and the ease of rescheduling anytime.",
  "Ringkasan Pesanan": "Order Summary",
  "Waktu": "Time",
  "Code Booking": "Booking Code",
  "Detail Pembayaran": "Payment Details",
  "Status Pembayaran": "Payment Status",
  "Waiting Pembayaran": "Waiting for Payment",
  "Bayar Sekarang": "Pay Now",
  "Lihat Detail": "View Details",
  "Datang Tepat Waktu": "Arrive on Time",
  "Tunjukkan Code": "Show Code",
  "Booking Success": "Booking Success",
  "Jl. Senopati No. 88, Kebayoran Baru, Jakarta Selatan.": "Senopati St. No. 88, Kebayoran Baru, South Jakarta.",
  " Sen ": " Mon ",
  " Sel ": " Tue ",
  " Rab ": " Wed ",
  " Kam ": " Thu ",
  " Jum ": " Fri ",
  " Sab ": " Sat ",
  " Min ": " Sun ",
  "Pembayaran gagal. Silakan coba lagi.": "Payment failed. Please try again.",
  "Failed memproses pembayaran.": "Failed to process payment.",
  "Gagal memuat status pesanan": "Failed to load order status",
  "sinkron status pembayaran of Midtrans ke database": "sync payment status from Midtrans to database",
  "Tidak ada booking ditemukan.": "No booking found.",
  "Gagal mendapatkan snap token": "Failed to get snap token",
  "Kesalahan tidak terduga saat memuat transaksi": "Unexpected error when loading transaction",
  "Revenue Harian": "Daily Revenue",
  "Revenue Per Bulan": "Monthly Revenue",
  "Bar hari ini berwarna kuning.": "Today is highlighted in yellow.",
  "All waktu — pilih bulan untuk lihat harian.": "All time — select month for daily view.",
  "Hari ini": "Today",
  "Bulan ini": "This Month",
  "Filter Laporan": "Report Filter",
  "Ekspor PDF": "Export PDF",
  "Dasbor": "Dashboard",
  "Total Pendapatan": "Total Revenue",
  "Total Transaksi": "Total Transactions",
  "Pelanggan Baru": "New Customers",
  "Antrian Hari Ini": "Today Queue",
  "Ubah Status": "Change Status",
  "Detail Transaksi": "Transaction Details",
  "Simpan Perubahan": "Save Changes",
  "Ya": "Yes",
  "Tidak": "No",
  "Gagal": "Failed",
  "Layanan Baru": "New Service",
  "Tambah": "Add",
  "Durasi": "Duration",
  "Menit": "Minutes",
  "Edit": "Edit",
  "Pilih": "Select",
  "Bulan": "Month",
  "Tahun": "Year",
  "Halaman": "Page",
  "dari": "of",
  "Eksekutif": "Executive",
  "Belum ditentukan": "Unassigned",
  "Tanpa Kapster": "No Barber",
  "Hari Ini": "Today",
  "hari ini": "today",
  "batal": "cancelled",
  "selesai": "completed",
  "Kunjungan Completed Today": "Visits Completed Today",
  "Status Today": "Today's Status",
  "Booking today": "Bookings today",
  "Completed Today": "Completed Today",
  "Sesi telah completed": "Session is completed",
  "Register Antrean Today": "Queue Register Today",
  "Register Customer Today": "Customer Register Today",
  "Success dilayani today": "Successfully served today",
  "Menampilkan": "Showing",
  "antrean today": "queue today",
  "Tunggu sebentar agar render completed": "Wait a moment for render to complete",
  "User tutup popup tanpa bayar — tidak perlu sinkron, status tetap unpaid": "User closed popup without paying — no sync needed, status remains unpaid",
  "Sesi Anda telah dijadwalkan. Silakan simpan kode booking di bawah ini untuk ditunjukkan kepada resepsionis.": "Your session has been scheduled. Please save the booking code below to show to the receptionist.",
  "hapus +62, spasi, dll": "remove +62, spaces, etc.",
  "sebelum kirim ke backend": "before sending to backend",
  "Otomatis hilangkan yang cancelled": "Automatically remove cancelled",
  "Tukang cukur handal kami siap memberikan": "Our skilled barbers are ready to deliver",
  "pelayanan terbaik untuk Anda.": "the best service for you.",
  "Cari Layanan...": "Search Services...",
  "Temukan gaya Anda selanjutnya...": "Find your next style...",
  "Kapster kami sangat teliti": "Our barbers are highly meticulous",
  "Keahlian yang tak tertandingi": "Unmatched expertise",
  "Pesan Sekarang": "Book Now",
  "Semua hak dilindungi": "All rights reserved",
  "Selamat Datang di": "Welcome to",
  "Pilih layanan, kapster, dan waktu yang sesuai dengan Anda.": "Select service, barber, and time that suits you.",
  "Ringkasan Hari Ini": "Today's Summary",
  "Total Booking Hari Ini": "Total Bookings Today",
  "Total Booking Today": "Total Bookings Today",
  "Ringkasan Today": "Today's Summary",
  "Completed Hari Ini": "Completed Today",
  "No ada deskripsi.": "No description available.",
  "Atur katalog layanan eksklusif Anda. Addkan, perbarui detail harga, poin reward, atau durasi perawatan untuk menjaga standar presisi atelier.": "Manage your exclusive service catalog. Add, update prices, reward points, or treatment durations to maintain the atelier's precision standards.",
  "Add-on dipilih setelah layanan utama": "Add-on selected after main service",
  "Klik untuk Unggah Image": "Click to Upload Image",
  "Antrean Baru:": "New Queue:",
  "Belum ada notifikasi": "No notifications",
  "Terdaftar di database": "Registered in database",
  "Log In sebagai member": "Log In as member",
  "untuk memilih kapster favorit Anda": "to choose your favorite barber",
  "Siapa Saja": "Anyone",
  "Belum dipilih": "Not selected",
  "Total Estimasi": "Total Estimated",
  "Select layanan dan waktu yang sesuai dengan jadwal Anda. Kami memastikan pengalaman premium untuk setiap sesi.": "Select service and time that suits your schedule. We ensure a premium experience for every session.",
  "Klik untuk melihat kapster": "Click to view barber",
  "Silakan pilih tanggal untuk melihat slot waktu.": "Please select a date to view time slots.",
  "Member Aktif": "Active Member",
  "MEMPROSES...": "PROCESSING...",
  "MASUK & LANJUTKAN": "LOGIN & CONTINUE",
  "Register di sini": "Register here",
  "Member Exclusive": "Member Exclusive",
  "Select ulang tanggal, waktu, dan kapster. Anda tidak akan dikenakan biaya tambahan.": "Select a new date, time, and barber. You will not be charged extra.",
  "Lupa Kata Sandi": "Forgot Password",
  "Back ke Email": "Back to Email",
  "Verifikasi Email Anda": "Verify Your Email",
  "Kami telah mengirimkan 6 digit kode verifikasi ke email": "We have sent a 6-digit verification code to the email",
  "Silakan masukkan kode tersebut di bawah ini.": "Please enter the code below.",
  "Atur Ulang Kata Sandi": "Reset Password",
  "No Ada Booking": "No Booking Available",
  "Anda belum memiliki booking aktif. Silakan buat reservasi terlebih dahulu.": "You do not have an active booking. Please make a reservation first.",
  "Back ke Beranda": "Back to Home",
  "Total Tagihan": "Total Bill",
  "Pembayaran aman melalui": "Secure payment via",
  "Kami mendukung GoPay, OVO, DANA, QRIS, Transfer Bank, dan Kartu Kredit.": "We support GoPay, OVO, DANA, QRIS, Bank Transfers, and Credit Cards.",
  "Code Unik Anda": "Your Unique Code",
  "Mohon hadir 10 menit sebelum jadwal untuk konsultasi awal.": "Please arrive 10 minutes early for an initial consultation.",
  "Save tangkapan layar ini dan tunjukkan ke resepsionis kami.": "Save this screenshot and show it to our receptionist.",
  "Lokasi di Peta": "Location on Map",
  "Koordinat yang tampil di landing page": "Coordinates displayed on the landing page",
  "Total Promo": "Total Promos",
  "Min Trx": "Min Trx",
  "Max Disc": "Max Disc",
  "Capping": "Capping",
  "Edit Kata Sandi (Optional)": "Edit Password (Optional)",
  "Kata Sandi": "Password",
  "Total Kunjungan": "Total Visits",
  "Nama Member": "Member Name",
  "Selamat datang kembali di Atelier Manajemen.": "Welcome back to the Atelier Management.",
  "Total Antrean": "Total Queue",
  "Sedang dilayani kapster": "Being served by barber",
  "Completed (Page Ini)": "Completed (This Page)",
  "Belum ada kapster di database.": "No barbers in database.",
  "Kelola Member": "Manage Members",
  "Total Membership": "Total Memberships",
  "Manajemen tim artis The Modern Artisan. Addkan staf baru, perbarui spesialisasi, atau atur status kehadiran mereka.": "Management of The Modern Artisan artist team. Add new staff, update specializations, or set their attendance status.",
  "Kelola Antrean": "Manage Queue",
  "Kelola Service": "Manage Services",
  "Kelola Barber": "Manage Barbers",
  "Kelola Booking": "Manage Bookings",
  "Kelola poin loyalitas dan pantau frekuensi kunjungan secara real-time.": "Manage loyalty points and monitor visit frequency in real-time.",
  "Direktori komprehensif pelanggan setia The Modern Artisan.": "Comprehensive directory of loyal customers of The Modern Artisan.",
  "Schedule Barber": "Barber Schedule",
  "'id-ID'": "'en-US'",
  "\"id-ID\"": "\"en-US\"",
  "Cari Code Unik atau Nama...": "Search Unique Code or Name...",
  "Cari Nama atau Code...": "Search Name or Code...",
  "today": "today",
  "Sedang Proses": "In Progress",
  "Estimasi Revenue": "Estimated Revenue",
  "Queue Register Today": "Today's Queue Register",
  "Menunggu": "Waiting",
  "No ada antrean untuk filter ini.": "No queue found for this filter.",
  "No ada antrean saat ini.": "No queue at the moment.",
  "No ada antrean": "No queue",
  "Semua antrean hari ini telah completed.": "All queues today are completed.",
  "Sedang dilayani": "Being served",
  "No. / Code": "No. / Code",
  "Nama Customer": "Customer Name",
  "Belum ada transaksi.": "No transactions yet.",
  "Belum ada": "Not available",
  "Lainnya": "Others",
  "Belum ada layanan tersedia.": "No services available.",
  "Belum ada data.": "No data available.",
  "Total Booking": "Total Bookings",
  "Total Barber": "Total Barbers",
  "Sebagai tamu, kapster terbaik yang sedang tersedia akan kami pilihkan secara otomatis untuk Anda.": "As a guest, the best available barber will be automatically selected for you.",
  "Acak Otomatis (Tamu)": "Auto Random (Guest)",
  "Butuh:": "Required:",
  "Poin Anda:": "Your Points:",
  "Pesan WA & Email berhasil diproses!": "WhatsApp & Email messages successfully processed!",
  "Pembayaran Anda sedang diproses. Harap completedkan sesuai instruksi.": "Your payment is being processed. Please complete according to the instructions.",
  "Lokasi Kami": "Our Location",
  "Dipilih otomatis oleh sistem": "Automatically selected by system",
  "Registrasi gagal. Silakan periksa kembali data Anda.": "Registration failed. Please double-check your data.",
  "Login gagal. Silakan periksa kembali data Anda.": "Login failed. Please double-check your data.",
  "Sesi Anda telah berakhir. Silakan isi data Guest atau Login kembali.": "Your session has expired. Please fill in Guest data or Login again.",
  "Lengkapi detail Anda untuk melanjutkan pemesanan layanan grooming terbaik.": "Complete your details to continue booking the best grooming services.",
  "Data Anda aman dan hanya digunakan untuk konfirmasi jadwal.": "Your data is safe and only used for schedule confirmation.",
  "Kami mencatat detail potongan rambut Anda untuk memastikan hasil yang konsisten setiap kali datang.": "We record your haircut details to ensure consistent results every time you visit.",
  "Silakan masukkan alamat email Anda.": "Please enter your email address.",
  "Code verifikasi telah berhasil dikirim ke email Anda.": "The verification code has been successfully sent to your email.",
  "Kata sandi Anda telah berhasil diperbarui.": "Your password has been successfully updated.",
  "Keamanan adalah prioritas kami. Ikuti langkah sederhana untuk memulihkan akses lengkap ke profil grooming premium Anda.": "Security is our priority. Follow these simple steps to restore full access to your premium grooming profile.",
  "Log Inkan alamat email terdaftar Anda di bawah ini. Kami akan mengirimkan 6 digit kode verifikasi untuk memvalidasi identitas Anda.": "Enter your registered email address below. We will send a 6-digit verification code to validate your identity.",
  "Alamat Email Anda": "Your Email Address",
  "Identitas Anda berhasil diverifikasi. Log Inkan kata sandi baru Anda di bawah ini untuk mereset akun Anda.": "Your identity has been successfully verified. Enter your new password below to reset your account.",
  "Periksa kembali data Anda": "Please double-check your data",
  "Sedang Processing": "Processing",
  "No dapat mengambil data pengaturan. Periksa koneksi Anda.": "Failed to fetch settings data. Please check your connection.",
  "Nama toko Anda...": "Your shop name...",
  "Kurasi perawatan pria terbaik untuk menonjolkan karakter dan kepercayaan diri Anda.": "Curating the best men's grooming to highlight your character and confidence.",
  "Beranda": "Home",
  "Kunjungi Kami": "Visit Us",
  "Lebih of sekadar potong rambut. Kami memberikan pengalaman perawatan pria yang": "More than just a haircut. We provide a men's grooming experience that",
  "Tim kami adalah seniman rambut bersertifikat dengan dedikasi tinggi pada detail.": "Our team consists of certified hair artists with high dedication to detail.",
  "Kami hanya menggunakan pomade dan skin-care artisan terbaik untuk kesehatan kulit Anda.": "We only use the best artisan pomades and skin-care for your skin's health.",
  "Dapatkan berbagai penawaran menarik khusus untuk member setia The Modern Artisan. Bergabunglah sekarang untuk menikmati potongan harga dan kumpulkan poin setiap kali Anda berkunjung.": "Get various attractive offers exclusively for loyal members of The Modern Artisan. Join now to enjoy discounts and collect points every time you visit.",
  "Pantau ketersediaan seniman rambut kami secara real-time untuk kunjungan yang lebih terencana.": "Monitor the availability of our hair artists in real-time for better-planned visits.",
  "Amankan slot Anda sekarang dan rasakan pengalaman potong rambut terbaik": "Secure your slot now and experience the best haircut",
  "Konfigurasi informasi barbershop, lokasi peta, jam operasional, dan keamanan akun admin.": "Configure barbershop information, map location, operational hours, and admin account security.",
  "Menyimpan...": "Saving...",
  "Save Perubahan": "Save Changes",
  "Information Barbershop": "Barbershop Information",
  "Nama Barbershop": "Barbershop Name",
  "Email Bisnis": "Business Email",
  "Nomor Telepon": "Phone Number",
  "Alamat Lengkap": "Complete Address",
  "Pratinjau": "Preview",
  "Keamanan Akun": "Account Security",
  "Edit Password Admin": "Edit Admin Password",
  "Password Saat Ini": "Current Password",
  "Password Baru (min. 6 karakter)": "New Password (min. 6 characters)",
  "Confirmation Password Baru": "Confirm New Password",
  "Save Password Baru": "Save New Password",
  "Nama": "Name",
  "Telepon": "Phone",
  "Alamat": "Address",
  "Koordinat": "Coordinates",
  "Buka di OpenStreetMap untuk mencari koordinat": "Open in OpenStreetMap to find coordinates",
  "Settings Sistem": "System Settings",
  "Pratinjau lokasi. Atur koordinat di bawah.": "Location preview. Set coordinates below.",
  "Manajemen jadwal kapster & ketersediaan kursi": "Barber schedule management & seat availability",
  "Akses ditolak. Anda bukan Admin.": "Access denied. You are not an Admin.",
  "Settings berhasil diperbarui.": "Settings successfully updated.",
  "Failed memuat pengaturan": "Failed to load settings",
  "Failed menyimpan pengaturan. Coba lagi.": "Failed to save settings. Try again.",
  "Failed mengubah password.": "Failed to change password.",
  "Password berhasil diubah.": "Password successfully changed.",
  "Confirmation password tidak cocok.": "Password confirmation does not match.",
  "Password baru minimal 6 karakter.": "New password must be at least 6 characters.",
  "All kolom password harus diisi.": "All password fields must be filled."
};

function walkSync(dir, filelist) {
  const files = fs.readdirSync(dir);
  filelist = filelist || [];
  files.forEach(function(file) {
    if (fs.statSync(path.join(dir, file)).isDirectory()) {
      if (file !== 'node_modules' && file !== '.git' && file !== 'dist') {
        filelist = walkSync(path.join(dir, file), filelist);
      }
    }
    else {
      const ext = path.extname(file);
      if (['.tsx', '.ts', '.php', '.jsx', '.js', '.blade.php'].includes(ext) || file.endsWith('.blade.php')) {
        filelist.push(path.join(dir, file));
      }
    }
  });
  return filelist;
}

const targetDirs = [
  path.join(__dirname, 'barber-react/src'),
  path.join(__dirname, 'barber-booking-api/app'),
  path.join(__dirname, 'barber-booking-api/resources/views')
];

console.log("Starting global scan to apply Master Dictionary...");
let filesToProcess = [];
targetDirs.forEach(dir => {
  if (fs.existsSync(dir)) {
    filesToProcess = filesToProcess.concat(walkSync(dir));
  }
});

let affectedCount = 0;
filesToProcess.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  let originalContent = content;
  
  // Sort keys by length descending to prevent partial substring mismatches
  const keys = Object.keys(dict).sort((a, b) => b.length - a.length);

  keys.forEach(id => {
    const en = dict[id];
    content = content.split(id).join(en);
  });

  if (content !== originalContent) {
    fs.writeFileSync(file, content, 'utf8');
    console.log("Applied translations to: " + file);
    affectedCount++;
  }
});
console.log("Done! Total files updated: " + affectedCount);
