/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-container-high': '#2a2a2a',
        'tertiary-fixed': '#e2e2e2',
        'secondary-fixed': '#e4e2e1',
        primary: '#eac249',
        'on-surface-variant': '#d0c5af',
        'surface-bright': '#393939',
        'primary-container': '#c5a028',
        'surface-container-highest': '#353534',
        background: '#131313',
        'on-background': '#e5e2e1',
        tertiary: '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-container': '#a3a4a4',
        'primary-fixed-dim': '#eac249',
        'error-container': '#93000a',
        'surface-container-low': '#1c1b1b',
        'on-primary-fixed-variant': '#584400',
        'surface-tint': '#eac249',
        'surface-dim': '#131313',
        'tertiary-fixed-dim': '#c6c6c6',
        error: '#ffb4ab',
        'primary-fixed': '#ffe08b',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#241a00',
        secondary: '#c8c6c5',
        'surface-container-lowest': '#0e0e0e',
        'secondary-container': '#474747',
        'on-tertiary-fixed-variant': '#454747',
        'surface-variant': '#353534',
        'on-error': '#690005',
        outline: '#99907c',
        'inverse-on-surface': '#313030',
        'on-secondary-fixed': '#1b1c1c',
        'on-primary-container': '#493800',
        'on-secondary': '#303030',
        'surface-container': '#201f1f',
        'on-surface': '#e5e2e1',
        'inverse-surface': '#e5e2e1',
        'on-tertiary': '#2f3131',
        'outline-variant': '#4d4635',
        'on-primary': '#3d2f00',
        'on-tertiary-container': '#393a3b',
        'on-secondary-fixed-variant': '#474747',
        'on-secondary-container': '#b6b5b4',
        'secondary-fixed-dim': '#c8c6c5',
        'inverse-primary': '#745b00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
